# for testing locally: 
# jekyll serve --config _config.yml,_config-dev.yml
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000/" # the base hostname & protocol for your site
